apiVersion: v1
kind: Service
metadata:
  name: bharat-app-lb
  namespace: bharat-app
spec:
  type: LoadBalancer
  selector:
    app: bharat-app
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 8000 # Pod container port

